# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increment the version code"
  lane :increment_version_code do
    increment_version_code(
      gradle_file: "app/build.gradle",
      version_code: 2
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build debug apk"
  lane :build_debug do
    gradle(task: "clean assembleDebug")
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    gradle(
      task: "bundle",
      build_type: "release"
    )
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      aab: "./app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
